// mutations.js
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_ID = 'SET_USER_ID';
export const SET_DEVICE_CODE = 'SET_DEVICE_CODE';
export const SET_DOCUMENT_COUNTING = 'SET_DOCUMENT_COUNTING';
export const SET_CURRENT_MAIN_COLOR = 'SET_CURRENT_MAIN_COLOR';
