// mutations.js
export const SET_USER_ID = 'SET_USER_ID';
export const SET_USER_EMAIL = 'SET_USER_EMAIL';
export const SET_USER_NAME = 'SET_USER_NAME';
export const SET_USER_LASTNAME = 'SET_USER_LASTNAME';
export const SET_USER_PROFILE_IMG = 'SET_USER_PROFILE_IMG';
export const SET_USER_BIRTHDATE = 'SET_USER_BIRTHDATE';
export const SET_USER_SEX = 'SET_USER_SEX';
export const SET_USER_WEIGHT = 'SET_USER_WEIGHT';
export const SET_USER_HEIGHT = 'SET_USER_HEIGHT';
export const SET_USER_COUNTRY = 'SET_USER_COUNTRY';
export const SET_USER_ADDRESS = 'SET_USER_ADDRESS';
export const SET_USER_PHONE = 'SET_USER_PHONE';
export const SET_USER_PROFESSION = 'SET_USER_PROFESSION';
export const SET_USER_COMPANY = 'SET_USER_COMPANY';
export const SET_USER_BLOODTYPE = 'SET_USER_BLOODTYPE';
export const SET_CLINIC_NAME = 'SET_CLINIC_NAME';
export const SET_CLINIC_ADDRESS = 'SET_CLINIC_ADDRESS';
export const SET_CLINIC_PHONE = 'SET_CLINIC_PHONE';
export const SET_DEVICE_CODE = 'SET_DEVICE_CODE';
export const SET_DOCUMENT_COUNTING = 'SET_DOCUMENT_COUNTING';
export const INCREMENT_DOCUMENT_COUNTING = 'INCREMENT_DOCUMENT_COUNTING';
export const DECREMENT_DOCUMENT_COUNTING = 'DECREMENT_DOCUMENT_COUNTING';
export const SET_CURRENT_MAIN_COLOR = 'SET_CURRENT_MAIN_COLOR';
export const SET_EMERGENCIES_CONTACT = 'SET_EMERGENCIES_CONTACT';
export const SET_INSURANCE_COMPANY = 'SET_INSURANCE_COMPANY';
export const SET_SOCIAL_SECURITY_NUMBER = 'SET_SOCIAL_SECURITY_NUMBER';

